// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-generated product recommendations based on a given product.
 *
 * - generateRecommendations - A function to generate product recommendations.
 * - GenerateRecommendationsInput - The input type for generateRecommendations function.
 * - GenerateRecommendationsOutput - The return type for generateRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecommendationsInputSchema = z.object({
  productDescription: z.string().describe('The description of the product for which recommendations are needed.'),
  productName: z.string().describe('The name of the product.'),
});

export type GenerateRecommendationsInput = z.infer<typeof GenerateRecommendationsInputSchema>;

const GenerateRecommendationsOutputSchema = z.object({
  recommendations: z.array(
    z.object({
      name: z.string().describe('The name of the recommended product.'),
      description: z.string().describe('A short description of the recommended product.'),
    })
  ).describe('A list of recommended products that complement the given product.'),
});

export type GenerateRecommendationsOutput = z.infer<typeof GenerateRecommendationsOutputSchema>;

export async function generateRecommendations(input: GenerateRecommendationsInput): Promise<GenerateRecommendationsOutput> {
  return generateRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRecommendationsPrompt',
  input: {schema: GenerateRecommendationsInputSchema},
  output: {schema: GenerateRecommendationsOutputSchema},
  prompt: `You are a personal stylist recommending complementary products based on a product the user is viewing.

  Based on the following product description and product name, recommend products that would enhance the user's style.

  Product Name: {{{productName}}}
  Product Description: {{{productDescription}}}

  Return a list of product recommendations. Ensure each recommendation has a name and a brief description.
  `,
});

const generateRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateRecommendationsFlow',
    inputSchema: GenerateRecommendationsInputSchema,
    outputSchema: GenerateRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
