import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic White Tee',
    brand: 'paknamae',
    description: 'A versatile and comfortable white tee, a staple for any wardrobe. Made from soft, high-quality cotton.',
    price: 45.00,
    category: 'Tops',
    image: 'https://i4.codibook.net/files/198212016603/4a3c82e447a057b9/20745727.jpg',
    dataAiHint: 'white tee',
  },
  {
    id: '2',
    name: 'High-Waisted Linen Trousers',
    brand: 'From Beginning',
    description: 'Effortlessly chic high-waisted trousers crafted from breathable linen. Features a wide-leg silhouette and a comfortable elasticated waistband.',
    price: 95.00,
    category: 'Bottoms',
    image: 'https://i3.codibook.net/files/1982100371404/0e666f6923db0a06/1060252598.jpg',
    dataAiHint: 'linen trousers',
  },
  {
    id: '3',
    name: 'Midnight Floral Midi Dress',
    brand: 'Loonough',
    description: 'A romantic midi dress adorned with a delicate midnight floral print. Designed with a flattering V-neckline and a flowing A-line skirt.',
    price: 155.00,
    category: 'Dresses',
    image: 'https://s3.codibook.net/codibook/2024/05/17/1c6d860d-0346-46c5-a359-bb43e9447e17.jpg',
    dataAiHint: 'floral dress',
  },
  {
    id: '4',
    name: 'Classic Trench Coat',
    brand: 'BOKPLACE',
    description: 'An iconic, double-breasted trench coat in a timeless beige. Made from water-resistant cotton gabardine, it\'s a versatile wardrobe staple.',
    price: 250.00,
    category: 'Outerwear',
    image: 'https://s3.codibook.net/codibook/2024/03/13/2827178c-0f9c-4ecf-94d0-a08b98bf8953.jpg',
    dataAiHint: 'trench coat',
  },
  {
    id: '5',
    name: 'Golden Orb Pendant',
    brand: 'wannabemuse',
    description: 'A minimalist pendant necklace featuring a polished golden orb on a delicate chain. Adds a touch of modern elegance to any outfit.',
    price: 75.00,
    category: 'Accessories',
    image: 'https://s3.codibook.net/codibook/2024/05/16/6f6f96cf-718e-4735-86a0-4f590ff9e17b.jpg',
    dataAiHint: 'gold necklace',
  },
  {
    id: '6',
    name: 'Cashmere Knit Sweater',
    brand: 'StyleNanda',
    description: 'Indulgently soft and warm, this crewneck sweater is spun from pure cashmere. A cozy essential for cooler days.',
    price: 180.00,
    category: 'Tops',
    image: 'https://s3.codibook.net/codibook/2024/05/13/9b46fbd0-6d43-43a0-8321-72f567b55e34.jpg',
    dataAiHint: 'cashmere sweater',
  },
  {
    id: '7',
    name: 'Pleated A-Line Skirt',
    brand: 'Chuu',
    description: 'A sophisticated A-line skirt with sharp pleats that create beautiful movement. Cut to a versatile midi length in a rich navy color.',
    price: 110.00,
    category: 'Bottoms',
    image: 'https://s3.codibook.net/codibook/2024/05/17/8e2029ca-e737-45e0-84c1-90209c1fa418.jpg',
    dataAiHint: 'pleated skirt',
  },
  {
    id: '8',
    name: 'Leather Crossbody Bag',
    brand: 'IMVELY',
    description: 'A compact and stylish crossbody bag crafted from supple Italian leather. Features a secure zip closure and an adjustable strap.',
    price: 195.00,
    category: 'Accessories',
    image: 'https://s3.codibook.net/codibook/2024/05/17/49a9000a-5c26-4763-9556-91e848604d55.jpg',
    dataAiHint: 'leather bag',
  },
  {
    id: '9',
    name: 'Sun-Kissed Wrap Dress',
    brand: 'Dabagirl',
    description: 'A vibrant wrap dress in a sun-kissed yellow, perfect for summer days. The wrap design creates a customizable and flattering fit.',
    price: 130.00,
    category: 'Dresses',
    image: 'https://s3.codibook.net/codibook/2024/05/17/472fe4c6-c2ba-4b2e-a579-deea4dafa9e9.jpg',
    dataAiHint: 'yellow dress',
  },
  {
    id: '10',
    name: 'Quilted Puffer Jacket',
    brand: 'ATTRANGS',
    description: 'Stay warm without sacrificing style in this lightweight quilted puffer jacket. Filled with eco-friendly insulation for superior warmth.',
    price: 210.00,
    category: 'Outerwear',
    image: 'https://s3.codibook.net/codibook/2024/02/19/2f170f7a-8d07-4228-89c5-8495f269a834.jpg',
    dataAiHint: 'puffer jacket',
  },
  {
    id: '11',
    name: 'Striped Cotton Tee',
    brand: '66girls',
    description: 'A wardrobe classic, this long-sleeve tee is made from soft, breathable cotton with timeless Breton stripes.',
    price: 55.00,
    category: 'Tops',
    image: 'https://s3.codibook.net/codibook/2024/05/16/e06b72a9-7c48-472d-ac15-d91d1e43d1a8.jpg',
    dataAiHint: 'striped shirt',
  },
  {
    id: '12',
    name: 'Denim A-Line Skirt',
    brand: 'SONA',
    description: 'A vintage-inspired A-line skirt made from structured denim. Features a button-front design and a flattering high-rise waist.',
    price: 85.00,
    category: 'Bottoms',
    image: 'https://s3.codibook.net/codibook/2024/05/17/4517336b-d36c-4b5b-801e-c76b7f300c7e.jpg',
    dataAiHint: 'denim skirt',
  },
];
