import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic White Tee',
    brand: 'SONA',
    description: 'A versatile and comfortable white tee, a staple for any wardrobe. Made from soft, high-quality cotton.',
    price: 45.00,
    category: 'Tops',
    image: 'https://i3.codibook.net/files/1982090162402/f8c8ca321872c7ae/480315438.jpg',
    dataAiHint: 'white t-shirt',
  },
  {
    id: '2',
    name: 'Classic Straight-Leg Jeans',
    brand: 'MERONGSHOP',
    description: 'A timeless pair of straight-leg jeans in a versatile medium wash. The perfect foundation for any casual outfit.',
    price: 89.00,
    category: 'Bottoms',
    image: 'https://i3.codibook.net/files/1982082951612/eec845f64deb3091/263733752.jpg',
    dataAiHint: 'blue jeans',
  },
  {
    id: '3',
    name: 'Elegant Black Midi Dress',
    brand: 'Loonough',
    description: 'An elegant black midi dress with a timeless silhouette. Perfect for any occasion, it features a classic neckline and a graceful, flowing skirt.',
    price: 155.00,
    category: 'Dresses',
    image: 'https://i3.codibook.net/files/1982111037201/cf7272c37de6b187/965439940.jpg',
    dataAiHint: 'black dress',
  },
  {
    id: '4',
    name: 'Classic Trench Coat',
    brand: 'BOKPLACE',
    description: 'An iconic, double-breasted trench coat in a timeless beige. Made from water-resistant cotton gabardine, it\'s a versatile wardrobe staple.',
    price: 250.00,
    category: 'Outerwear',
    image: 'https://i3.codibook.net/files/1982102326424/f1ec0fb57fcbf3e1/423208310.jpg',
    dataAiHint: 'trench coat',
  },
  {
    id: '5',
    name: 'Golden Orb Pendant',
    brand: 'wannabemuse',
    description: 'A minimalist pendant necklace featuring a polished golden orb on a delicate chain. Adds a touch of modern elegance to any outfit.',
    price: 75.00,
    category: 'Accessories',
    image: 'https://i3.codibook.net/files/1980112673220/52a41dafe36b6c28/87541929.jpg',
    dataAiHint: 'gold necklace',
  },
  {
    id: '6',
    name: 'Cashmere Knit Sweater',
    brand: 'StyleNanda',
    description: 'Indulgently soft and warm, this crewneck sweater is spun from pure cashmere. A cozy essential for cooler days.',
    price: 180.00,
    category: 'Tops',
    image: 'https://i4.codibook.net/files/1982112615608/7e0c5ad229c12bea/471930924.jpg',
    dataAiHint: 'cashmere sweater',
  },
  {
    id: '7',
    name: 'Pleated A-Line Skirt',
    brand: 'Chuu',
    description: 'A sophisticated A-line skirt with sharp pleats that create beautiful movement. Cut to a versatile midi length in a chic beige.',
    price: 110.00,
    category: 'Bottoms',
    image: 'https://i3.codibook.net/files/1982111055202/6fc1c8824b6f1014/134076189.jpg',
    dataAiHint: 'pleated skirt',
  },
  {
    id: '8',
    name: 'Leather Crossbody Bag',
    brand: 'IMVELY',
    description: 'A compact and stylish crossbody bag crafted from supple Italian leather. Features a secure zip closure and an adjustable strap.',
    price: 195.00,
    category: 'Accessories',
    image: 'https://i4.codibook.net/files/1982112735404/26511a24babf61f6/1546042652.jpg',
    dataAiHint: 'leather bag',
  },
  {
    id: '9',
    name: 'Sun-Kissed Wrap Dress',
    brand: 'Dabagirl',
    description: 'A vibrant wrap dress in a sun-kissed yellow, perfect for summer days. The wrap design creates a customizable and flattering fit.',
    price: 130.00,
    category: 'Dresses',
    image: 'https://i3.codibook.net/files/1981051619220/3a4c016e64ac5b48/1490629217.jpg',
    dataAiHint: 'yellow dress',
  },
  {
    id: '10',
    name: 'Linen Blend Blazer',
    brand: 'ATTRANGS',
    description: 'A chic and lightweight blazer made from a comfortable linen blend. Perfect for layering over dresses or tops for a polished look.',
    price: 150.00,
    category: 'Outerwear',
    image: 'https://i3.codibook.net/files/198209253003/755663b091b82be9/1182928204.jpg',
    dataAiHint: 'linen blazer',
  },
  {
    id: '11',
    name: 'Ribbed Knit Top',
    brand: '66girls',
    description: 'A flattering and versatile ribbed knit top. A comfortable and stylish piece for any casual occasion.',
    price: 55.00,
    category: 'Tops',
    image: 'https://i3.codibook.net/files/1982091867855/cae25e234e820dc6/1634501511.jpg',
    dataAiHint: 'white top',
  },
  {
    id: '12',
    name: 'Classic Black Trousers',
    brand: 'SONA',
    description: 'Timeless black trousers with a clean silhouette, perfect for both office and casual wear.',
    price: 85.00,
    category: 'Bottoms',
    image: 'https://i3.codibook.net/files/1982090166002/e43fb48bcc159ee1/422840155.jpg',
    dataAiHint: 'black trousers',
  },
];
