import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Azure Silk Blouse',
    description: 'A luxurious silk blouse in a vibrant azure hue, featuring a classic collar and button-front closure. Perfect for both office and evening wear.',
    price: 120.00,
    category: 'Tops',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'silk blouse',
  },
  {
    id: '2',
    name: 'High-Waisted Linen Trousers',
    description: 'Effortlessly chic high-waisted trousers crafted from breathable linen. Features a wide-leg silhouette and a comfortable elasticated waistband.',
    price: 95.00,
    category: 'Bottoms',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'linen trousers',
  },
  {
    id: '3',
    name: 'Midnight Floral Midi Dress',
    description: 'A romantic midi dress adorned with a delicate midnight floral print. Designed with a flattering V-neckline and a flowing A-line skirt.',
    price: 155.00,
    category: 'Dresses',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'floral dress',
  },
  {
    id: '4',
    name: 'Classic Trench Coat',
    description: 'An iconic, double-breasted trench coat in a timeless beige. Made from water-resistant cotton gabardine, it\'s a versatile wardrobe staple.',
    price: 250.00,
    category: 'Outerwear',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'trench coat',
  },
  {
    id: '5',
    name: 'Golden Orb Pendant',
    description: 'A minimalist pendant necklace featuring a polished golden orb on a delicate chain. Adds a touch of modern elegance to any outfit.',
    price: 75.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'gold necklace',
  },
  {
    id: '6',
    name: 'Cashmere Knit Sweater',
    description: 'Indulgently soft and warm, this crewneck sweater is spun from pure cashmere. A cozy essential for cooler days.',
    price: 180.00,
    category: 'Tops',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'cashmere sweater',
  },
  {
    id: '7',
    name: 'Pleated A-Line Skirt',
    description: 'A sophisticated A-line skirt with sharp pleats that create beautiful movement. Cut to a versatile midi length in a rich navy color.',
    price: 110.00,
    category: 'Bottoms',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'pleated skirt',
  },
  {
    id: '8',
    name: 'Leather Crossbody Bag',
    description: 'A compact and stylish crossbody bag crafted from supple Italian leather. Features a secure zip closure and an adjustable strap.',
    price: 195.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'leather bag',
  },
  {
    id: '9',
    name: 'Sun-Kissed Wrap Dress',
    description: 'A vibrant wrap dress in a sun-kissed yellow, perfect for summer days. The wrap design creates a customizable and flattering fit.',
    price: 130.00,
    category: 'Dresses',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'yellow dress',
  },
  {
    id: '10',
    name: 'Quilted Puffer Jacket',
    description: 'Stay warm without sacrificing style in this lightweight quilted puffer jacket. Filled with eco-friendly insulation for superior warmth.',
    price: 210.00,
    category: 'Outerwear',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'puffer jacket',
  },
  {
    id: '11',
    name: 'Striped Cotton Tee',
    description: 'A wardrobe classic, this long-sleeve tee is made from soft, breathable cotton with timeless Breton stripes.',
    price: 55.00,
    category: 'Tops',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'striped shirt',
  },
  {
    id: '12',
    name: 'Denim A-Line Skirt',
    description: 'A vintage-inspired A-line skirt made from structured denim. Features a button-front design and a flattering high-rise waist.',
    price: 85.00,
    category: 'Bottoms',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'denim skirt',
  },
];
